var app=new Vue({
    el:"#app",
    data:{
        pageInfo:'',
        pageNum:1,
        jname:''
    },
    mounted(){
        console.log('helow');
        this.queryList();
    },
    methods:{
        pageChange(val){
            this.pageNum=val;
            this.queryList();
        },
        queryList(){
            axios.get('http://localhost:8080/list/queryjszList',{
                params:{
                    pageNum:this.pageNum,
                    jname:this.jname
                }
            })
            .then(function(response){
                console.log(response);
                app.pageInfo=response.data;
            })
            .catch(function(error){
                console.log(error);
            });
        },
        sou(){
            this.queryList();
        },
        handleClick(row){
            location.href="search.html";
        },
        add(){
            location.href="add.html";
        },
        update(row){
            location.href="update.html?jid="+row.jid;
        }
    }
});